### ISSUE TITLE
句子长度问题

### ISSUE THREAD

**Issue by zcdliuwei** [liuhuanyong/SiameseSentenceSimilarity#11]
您好，看您代码，句子是全部处理成了固定长度，这个长度是这样选择的：通过collections.Counter构造计数器，倒排序单词数最多的句子对，然后对单词数最多的句子频数除以句子个数，将这个比率一直累加下去，直到它超过一个给定的阈值，也就是保证覆盖大部分句子，然后选择阈值处那个句子的单词数作为最终长度。因为Counter使用了倒排序以及接近1的阈值，那么选择出来的长度假设是10，也就是说，10个单词长度的句子，在全部训练集中出现的次数是比较少的，也就是大部分句子长度要么大于10要么小于10，而且因为要把全部句子处理成10的长度，会不会出现这样一种情况：假设很多句子长度大于10，通过截断到10的长度，会不会损失了很多信息 ？

**Comment by qiao1024** [comment]
> 您好，看您代码，句子是全部处理成了固定长度，这个长度是这样选择的：通过collections.Counter构造计数器，倒排序单词数最多的句子对，然后对单词数最多的句子频数除以句子个数，将这个比率一直累加下去，直到它超过一个给定的阈值，也就是保证覆盖大部分句子，然后选择阈值处那个句子的单词数作为最终长度。因为Counter使用了倒排序以及接近1的阈值，那么选择出来的长度假设是10，也就是说，10个单词长度的句子，在全部训练集中出现的次数是比较少的，也就是大部分句子长度要么大于10要么小于10，而且因为要把全部句子处理成10的长度，会不会出现这样一种情况：假设很多句子长度大于10，通过截断到10的长度，会不会损失了很多信息 ？

您好，您把代码跑通了嘛？
