### ISSUE TITLE
Keras 版本

### ISSUE THREAD

**Issue by yanqiangmiffy** [liuhuanyong/SiameseSentenceSimilarity#2]
`TypeError: Layer input_3 does not support masking, but was passed an input_mask: Tensor("embedding_1/NotEqual:0", shape=(?, 25), dtype=bool)`

你好请问下 Keras的本是多少，我查了下上面的错误，应该是版本的问题

**Comment by yanqiangmiffy** [comment]
2.2.4

**Comment by jockeyyan** [comment]
你好，对tensorflow版本的最低要求是？
